# Generated by Django 2.0.9 on 2019-12-05 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='teacher',
            field=models.ManyToManyField(blank=True, to='users.Profesor'),
        ),
    ]
