# Generated by Django 2.0.9 on 2019-12-05 20:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_curso_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='start',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 12, 5, 20, 33, 20, 869793, tzinfo=utc)),
        ),
    ]
